services:

    TgBotApi\BotApiBase\ApiClient:
        arguments:
            $requestFactory: '@Psr\Http\Message\RequestFactoryInterface'
            $streamFactory: '@Psr\Http\Message\StreamFactoryInterface'
            $client: '@Psr\Http\Client\ClientInterface'

    TgBotApi\BotApiBase\BotApiNormalizer: null

    TgBotApi\BotApiBase\ApiClientInterface: '@TgBotApi\BotApiBase\ApiClient'
    TgBotApi\BotApiBase\NormalizerInterface: '@TgBotApi\BotApiBase\BotApiNormalizer'

    TgBotApi\BotApiBase\BotApi:
        arguments:
            $botKey: '%env(resolve:TG_BOT_API_KEY)%'
            $apiClient: '@TgBotApi\BotApiBase\ApiClientInterface'
            $normalizer:  '@TgBotApi\BotApiBase\NormalizerInterface'

    TgBotApi\BotApiBase\BotApiComplete:
        parent: TgBotApi\BotApiBase\BotApi

    TgBotApi\BotApiBase\BotApiInterface: '@TgBotApi\BotApiBase\BotApi'
